/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#353944',
        'on-secondary-container': '#00374d',
        'secondary-fixed-dim': '#7bd0ff',
        'surface': '#0f131d',
        'on-primary-fixed-variant': '#6900b3',
        'on-secondary': '#00354a',
        'on-primary-fixed': '#2c0051',
        'primary': '#ddb7ff',
        'on-tertiary': '#490081',
        'surface-container-high': '#262a35',
        'inverse-on-surface': '#2c303b',
        'on-tertiary-fixed-variant': '#62259b',
        'surface-container-highest': '#313540',
        'on-secondary-fixed-variant': '#004c69',
        'outline-variant': '#4d4354',
        'surface-container': '#1c1f2a',
        'on-background': '#dfe2f1',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed': '#001e2c',
        'primary-fixed': '#f0dbff',
        'tertiary': '#ddb8ff',
        'tertiary-fixed-dim': '#ddb8ff',
        'on-surface-variant': '#cfc2d6',
        'on-primary': '#490080',
        'primary-container': '#b76dff',
        'on-tertiary-fixed': '#2c0051',
        'on-surface': '#dfe2f1',
        'surface-variant': '#313540',
        'on-primary-container': '#400071',
        'inverse-surface': '#dfe2f1',
        'surface-tint': '#ddb7ff',
        'inverse-primary': '#842bd2',
        'tertiary-fixed': '#f0dbff',
        'tertiary-container': '#b175ec',
        'background': '#0f131d',
        'on-error': '#690005',
        'on-tertiary-container': '#400071',
        'error-container': '#93000a',
        'surface-container-lowest': '#0a0e18',
        'outline': '#988d9f',
        'surface-dim': '#0f131d',
        'surface-container-low': '#171b26',
        'primary-fixed-dim': '#ddb7ff',
        'secondary': '#7bd0ff',
        'secondary-container': '#00a6e0',
        'secondary-fixed': '#c4e7ff',
        'error': '#ffb4ab',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'gutter-mobile': '1rem',
        'margin-mobile': '1.25rem',
        'space-xl': '2.5rem',
        'space-lg': '1.5rem',
        'gutter': '1.5rem',
        'margin': '2rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Plus Jakarta Sans', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-code': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.12em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'display-hero': ['64px', { lineHeight: '72px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'display-hero-mobile': ['38px', { lineHeight: '46px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%': { opacity: '0.5' },
          '100%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
